---
title: "Data for One Number Story"
author: "Maggie Wang"
date: "February 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
```

```{r}
# pull in data
edu_orig <- read.csv("MA_Public_Schools_2017.csv")
```

```{r}
# Explore and select variables

# Only look at high schools
edu <- edu_orig %>% 
  mutate(Grade = as.character(Grade)) %>%
  filter(endsWith(Grade, "09,10,11,12")) %>%
  select(School.Code, Grade, District.Name, Town, 26:29,
         High.Needs, Economically.Disadvantaged, 
         42:50, Average.In.District.Expenditures.per.Pupil,
         Average.Expenditures.per.Pupil, X..Dropped.Out,  
         MCAS_10thGrade_English_P.A.., MCAS_10thGrade_English_W.F..,
         MCAS_10thGrade_Math_P.A.., MCAS_10thGrade_Math_W.F.., 
         297:298) %>% 
  mutate(total_enroll = X9_Enrollment + X10_Enrollment + 
           X11_Enrollment + X12_Enrollment, 
         dropout = (X..Dropped.Out * total_enroll)/100, 
         black = (X..African.American * total_enroll)/100, 
         white = (X..White * total_enroll)/100, 
         hispanic = (X..Hispanic * total_enroll)/100, 
         asian = (X..Asian * total_enroll)/100, 
         other_re = (X..Native.American + X..Native.Hawaiian..Pacific.Islander + 
                    X..Multi.Race..Non.Hispanic) * total_enroll/100, 
         male = (X..Males * total_enroll)/100, 
         female = (X..Females * total_enroll)/100) %>% 
  rename("district" = "District.Name",  
         "enroll_10" = "X10_Enrollment", "high_need" = "High.Needs", 
         "econ_dis" = "Economically.Disadvantaged", "town" = "Town", 
         "avg_dist_exp_p" = "Average.In.District.Expenditures.per.Pupil", 
         "avg_exp_p" = "Average.Expenditures.per.Pupil", 
         "mcas_10_eng_pa" = "MCAS_10thGrade_English_P.A..", 
         "mcas_10_eng_wf" = "MCAS_10thGrade_English_W.F..", 
         "mcas_10_mth_pa" = "MCAS_10thGrade_Math_P.A..", 
         "mcas_10_mth_wf" = "MCAS_10thGrade_Math_W.F..", 
         "ppi_all" = "Progress.and.Performance.Index..PPI....All.Students", 
         "ppi_high_need" = "Progress.and.Performance.Index..PPI....High.Needs.Students") %>% 
  select(district, town, total_enroll, enroll_10,
         high_need, econ_dis, dropout, 
         black, white, hispanic, asian, other_re,
         male, female, avg_dist_exp_p, avg_exp_p, 
         mcas_10_eng_pa, mcas_10_eng_wf, 
         mcas_10_mth_pa, mcas_10_mth_wf,
         ppi_all, ppi_high_need)
```

```{r}
# Calculate town/district total
edu_town_district <- edu %>% 
  group_by(town, district) %>% 
  summarize(n_school = n(), enroll = sum(total_enroll), 
            enroll_10 = sum(enroll_10),
            dropout = sum(dropout),
            high_need = sum(high_need), 
            econ_dis = sum(econ_dis), 
            black = sum(black), white = sum(white), 
            hispanic = sum(hispanic), asian = sum(asian), 
            other_re = sum(other_re), male = sum(male), 
            female = sum(female), 
            avg_dist_exp_p = median(avg_dist_exp_p, na.rm = TRUE), 
            avg_exp_p = median(avg_exp_p, na.rm = TRUE), 
            mcas_10_eng_pa = sum(mcas_10_eng_pa, na.rm = TRUE), 
            mcas_10_eng_wf = sum(mcas_10_eng_wf, na.rm = TRUE), 
            mcas_10_mth_pa = sum(mcas_10_mth_pa, na.rm = TRUE), 
            mcas_10_mth_wf = sum(mcas_10_mth_wf, na.rm = TRUE), 
            ppi_all = mean(ppi_all, na.rm = TRUE),
            ppi_high_need = mean(ppi_high_need, na.rm = TRUE))

```

```{r}
# Calculate the Boston rates
edu_district_bos <- edu %>% 
  mutate(district = as.character(district)) %>% 
  filter(startsWith(district, "Boston") | town == "Boston") %>% 
  summarize(n_school = n(), enroll = sum(total_enroll, na.rm = TRUE), 
            enroll_10 = sum(enroll_10, na.rm = TRUE),
            dropout = sum(dropout, na.rm = TRUE),
            high_need = sum(high_need, na.rm = TRUE), 
            econ_dis = sum(econ_dis, na.rm = TRUE), 
            black = sum(black), white = sum(white), 
            hispanic = sum(hispanic), asian = sum(asian), 
            other_re = sum(other_re), male = sum(male), 
            female = sum(female), 
            avg_dist_exp_p = median(avg_dist_exp_p, na.rm = TRUE), 
            avg_exp_p = median(avg_exp_p, na.rm = TRUE), 
            mcas_10_eng_pa = sum(mcas_10_eng_pa, na.rm = TRUE), 
            mcas_10_eng_wf = sum(mcas_10_eng_wf, na.rm = TRUE), 
            mcas_10_mth_pa = sum(mcas_10_mth_pa, na.rm = TRUE), 
            mcas_10_mth_wf = sum(mcas_10_mth_wf, na.rm = TRUE), 
            ppi_all = mean(ppi_all, na.rm = TRUE),
            ppi_high_need = mean(ppi_high_need, na.rm = TRUE)) %>% 
  mutate(dropout = dropout/enroll, 
         high_need = high_need/enroll, 
         econ_dis = econ_dis/enroll, 
         black = black/enroll, white = white/enroll, 
         hispanic = hispanic/enroll, asian = asian/enroll, 
         other_re = other_re/enroll, male = male/enroll, 
         female = female/enroll, 
         mcas_10_eng_pa = mcas_10_eng_pa/enroll_10, 
         mcas_10_eng_wf = mcas_10_eng_wf/enroll_10,
         mcas_10_mth_pa = mcas_10_mth_pa/enroll_10, 
         mcas_10_mth_wf = mcas_10_mth_wf/enroll_10)
```


```{r}
phoenix_charter <- edu_orig %>% 
  filter(School.Name == "Phoenix Charter Academy")
```


```{r}
edu_town <- edu_town_district %>% 
  group_by(town) %>% 
  summarise(n_school = sum(n_school), 
            enroll = sum(enroll), 
            dropout = sum(dropout), 
            high_need = sum(high_need), 
            econ_dis = sum(econ_dis), 
            black = sum(black), white = sum(white), 
            hispanic = sum(hispanic), asian = sum(asian), 
            other_re = sum(other_re))

edu_town <- edu_town %>% 
  mutate(dropout = dropout/enroll, 
         high_need = high_need/enroll, 
         econ_dis = econ_dis/enroll, 
         black = black/enroll, white = white/enroll, 
         hispanic = hispanic/enroll, asian = asian/enroll, 
         other_re = other_re/enroll)
```

```{r}
top_drop_town <- edu_town %>% 
  filter(dropout >= 0.10)

boston_drop <- edu_town_district %>% 
  filter(district == "Boston" || town == "Boston") %>% 
  group_by(town, district) %>% 
  mutate(dropout = dropout/enroll, 
         high_need = high_need/enroll, 
         econ_dis = econ_dis/enroll, 
         black = black/enroll, white = white/enroll, 
         hispanic = hispanic/enroll, asian = asian/enroll, 
         other_re = other_re/enroll)

boston_drop_town <- edu_town_district %>% 
  filter(district == "Boston" || town == "Boston") %>% 
  group_by(town) %>% 
  summarise(n_school = sum(n_school, na.rm = TRUE), 
            enroll = sum(enroll, na.rm = TRUE), 
            dropout = sum(dropout, na.rm = TRUE), 
            high_need = sum(high_need, na.rm = TRUE), 
            econ_dis = sum(econ_dis, na.rm = TRUE), 
            black = sum(black, na.rm = TRUE), 
            white = sum(white, na.rm = TRUE), 
            hispanic = sum(hispanic, na.rm = TRUE),
            asian = sum(asian, na.rm = TRUE), 
            other_re = sum(other_re, na.rm = TRUE)) %>% 
  mutate(dropout = dropout/enroll, 
         high_need = high_need/enroll, 
         econ_dis = econ_dis/enroll, 
         black = black/enroll, white = white/enroll, 
         hispanic = hispanic/enroll, asian = asian/enroll, 
         other_re = other_re/enroll)

```

